name: Update wakatime

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: '1 8 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: bhanukaManesha/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          MORNING_PERSON: "True"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
